language: r
cache: packages
os: linux

jobs:
  include:
    - os: linux
      r: release
      env: R_CODECOV=true
    - os: linux
      r: devel
      env: _R_CHECK_LENGTH_1_LOGIC2_=TRUE

addons:
  apt:
    packages:
      - libpoppler-cpp-dev

r_packages:
  - covr

r_check_args: "--as-cran --run-dontrun --no-build-vignettes"

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

notifications:
  email:
    on_success: change
    on_failure: change
